# Generated by Django 4.2.21 on 2025-06-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
